#! /usr/bin/env bash

# If homebrew functions directory is not in fpath, add it

PREF="${HOMEBREW_PREFIX:-/usr/local}"
FDIR="/share/zsh/site-functions"

if
  echo $FPATH | grep -q "${PREF}/${FDIR}"
then
  echo "FPATH contains ${PREF}/${FDIR}"
else
  echo "Adding Homebrew functions to zsh function path"
  echo "\n# added by postinstall of product ${PWD##*/}\n" >> ~/.zshenv
  echo "FPATH=${FPATH}:${PREF}/${FDIR}" >> ~/.zshenv
fi
