#! /usr/bin/env bash

# If homebrew functions directory is not in fpath, add it

PREF="${HOMEBREW_PREFIX:-/usr/local}"
FDIR="/share/zsh/site-functions"

eval HOMED=~$(whoami)
if
  echo $FPATH | grep -q "${PREF}/${FDIR}"
then
  echo "FPATH already contains ${PREF}/${FDIR}"
else
  echo "Add Homebrew functions path ${PREF}/${FDIR} to zsh function path in ${HOMED}/.zshenv"
fi
